# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

requirements:
  - sphinx==7.4.7
  - sphinx-rtd-theme==2.0.0
  - sphinxcontrib-applehelp==2.0.0
  - sphinxcontrib-devhelp==2.0.0
  - sphinxcontrib-htmlhelp==2.0.0
  - sphinxcontrib-jquery==4.1
  - sphinxcontrib-jsmath==1.0.1
  - sphinxcontrib-qthelp==2.0.0
  - sphinxcontrib-serializinghtml==2.0.0
  - PySide6==6.2.2.1
