# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiWidgetMaskSegment4.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_segment4_parameter = QtWidgets.QLabel(Form)
        self.label_segment4_parameter.setObjectName("label_segment4_parameter")
        self.verticalLayout_14.addWidget(self.label_segment4_parameter)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_segment4_inner = QtWidgets.QLabel(Form)
        self.label_segment4_inner.setObjectName("label_segment4_inner")
        self.horizontalLayout_25.addWidget(self.label_segment4_inner)
        self.doubleSpinBox_segment4_inner = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_segment4_inner.setObjectName("doubleSpinBox_segment4_inner")
        self.horizontalLayout_25.addWidget(self.doubleSpinBox_segment4_inner)
        self.verticalLayout_14.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_segment4_outer = QtWidgets.QLabel(Form)
        self.label_segment4_outer.setObjectName("label_segment4_outer")
        self.horizontalLayout_26.addWidget(self.label_segment4_outer)
        self.doubleSpinBox_segment4_outer = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_segment4_outer.setObjectName("doubleSpinBox_segment4_outer")
        self.horizontalLayout_26.addWidget(self.doubleSpinBox_segment4_outer)
        self.verticalLayout_14.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_segment4_rotate_angle = QtWidgets.QLabel(Form)
        self.label_segment4_rotate_angle.setObjectName("label_segment4_rotate_angle")
        self.horizontalLayout_27.addWidget(self.label_segment4_rotate_angle)
        self.doubleSpinBox_segment4_rotate_angle = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_segment4_rotate_angle.setObjectName("doubleSpinBox_segment4_rotate_angle")
        self.horizontalLayout_27.addWidget(self.doubleSpinBox_segment4_rotate_angle)
        self.verticalLayout_14.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_segment4_open_angle = QtWidgets.QLabel(Form)
        self.label_segment4_open_angle.setObjectName("label_segment4_open_angle")
        self.horizontalLayout_28.addWidget(self.label_segment4_open_angle)
        self.doubleSpinBox_segment4_open_angle = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_segment4_open_angle.setObjectName("doubleSpinBox_segment4_open_angle")
        self.horizontalLayout_28.addWidget(self.doubleSpinBox_segment4_open_angle)
        self.verticalLayout_14.addLayout(self.horizontalLayout_28)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem)
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_14.addWidget(self.line_5)
        self.checkBox_segment4_is_center = QtWidgets.QCheckBox(Form)
        self.checkBox_segment4_is_center.setObjectName("checkBox_segment4_is_center")
        self.verticalLayout_14.addWidget(self.checkBox_segment4_is_center)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_segment4_center_j = QtWidgets.QLabel(Form)
        self.label_segment4_center_j.setObjectName("label_segment4_center_j")
        self.horizontalLayout_29.addWidget(self.label_segment4_center_j)
        self.doubleSpinBox_segment4_center_j = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_segment4_center_j.setObjectName("doubleSpinBox_segment4_center_j")
        self.horizontalLayout_29.addWidget(self.doubleSpinBox_segment4_center_j)
        self.verticalLayout_14.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_segment4_center_i = QtWidgets.QLabel(Form)
        self.label_segment4_center_i.setObjectName("label_segment4_center_i")
        self.horizontalLayout_30.addWidget(self.label_segment4_center_i)
        self.doubleSpinBox_segment4_center_i = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_segment4_center_i.setObjectName("doubleSpinBox_segment4_center_i")
        self.horizontalLayout_30.addWidget(self.doubleSpinBox_segment4_center_i)
        self.verticalLayout_14.addLayout(self.horizontalLayout_30)
        self.verticalLayout.addLayout(self.verticalLayout_14)
        self.label_segment4_inner.setBuddy(self.doubleSpinBox_segment4_inner)
        self.label_segment4_outer.setBuddy(self.doubleSpinBox_segment4_outer)
        self.label_segment4_rotate_angle.setBuddy(self.doubleSpinBox_segment4_rotate_angle)
        self.label_segment4_open_angle.setBuddy(self.doubleSpinBox_segment4_open_angle)
        self.label_segment4_center_j.setBuddy(self.doubleSpinBox_segment4_center_j)
        self.label_segment4_center_i.setBuddy(self.doubleSpinBox_segment4_center_i)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_segment4_parameter.setText(_translate("Form", "Four-segmented ring parameters"))
        self.label_segment4_inner.setText(_translate("Form", "inner radius (pix)(&I)"))
        self.label_segment4_outer.setText(_translate("Form", "outer radius (pix)(&O)"))
        self.label_segment4_rotate_angle.setText(_translate("Form", "rotation angle (deg)(&R)"))
        self.label_segment4_open_angle.setText(_translate("Form", "open angle (deg)(&A)"))
        self.checkBox_segment4_is_center.setText(_translate("Form", "centered"))
        self.label_segment4_center_j.setText(_translate("Form", "horizontal shift(&J)"))
        self.label_segment4_center_i.setText(_translate("Form", "vertical shift(&I)"))

