# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiWidgetPreviewDP.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(524, 509)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = WidgetImageViewDP(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_scan_x = QtWidgets.QLabel(Form)
        self.label_scan_x.setObjectName("label_scan_x")
        self.horizontalLayout.addWidget(self.label_scan_x)
        self.spinBox_scan_x = QtWidgets.QSpinBox(Form)
        self.spinBox_scan_x.setObjectName("spinBox_scan_x")
        self.horizontalLayout.addWidget(self.spinBox_scan_x)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_scan_y = QtWidgets.QLabel(Form)
        self.label_scan_y.setObjectName("label_scan_y")
        self.horizontalLayout_2.addWidget(self.label_scan_y)
        self.spinBox_scan_y = QtWidgets.QSpinBox(Form)
        self.spinBox_scan_y.setObjectName("spinBox_scan_y")
        self.horizontalLayout_2.addWidget(self.spinBox_scan_y)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.comboBox_cmap = QtWidgets.QComboBox(Form)
        self.comboBox_cmap.setObjectName("comboBox_cmap")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_cmap)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.comboBox_norm = QtWidgets.QComboBox(Form)
        self.comboBox_norm.setObjectName("comboBox_norm")
        self.comboBox_norm.addItem("")
        self.comboBox_norm.addItem("")
        self.comboBox_norm.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_norm)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_adjust_cmap = QtWidgets.QPushButton(Form)
        self.pushButton_adjust_cmap.setObjectName("pushButton_adjust_cmap")
        self.horizontalLayout_3.addWidget(self.pushButton_adjust_cmap)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.label_scan_x.setBuddy(self.spinBox_scan_x)
        self.label_scan_y.setBuddy(self.spinBox_scan_y)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_scan_x.setText(_translate("Form", "X scanning coordinades(&X)"))
        self.label_scan_y.setText(_translate("Form", "Y scanning coordinates(&Y)"))
        self.label.setText(_translate("Form", "choose color map"))
        self.comboBox_cmap.setItemText(0, _translate("Form", "default"))
        self.comboBox_cmap.setItemText(1, _translate("Form", "autumn"))
        self.comboBox_cmap.setItemText(2, _translate("Form", "binary"))
        self.comboBox_cmap.setItemText(3, _translate("Form", "cividis"))
        self.comboBox_cmap.setItemText(4, _translate("Form", "gray"))
        self.comboBox_cmap.setItemText(5, _translate("Form", "hsv"))
        self.comboBox_cmap.setItemText(6, _translate("Form", "jet"))
        self.comboBox_cmap.setItemText(7, _translate("Form", "plasma"))
        self.comboBox_cmap.setItemText(8, _translate("Form", "spring"))
        self.comboBox_cmap.setItemText(9, _translate("Form", "summer"))
        self.comboBox_cmap.setItemText(10, _translate("Form", "twilight"))
        self.comboBox_cmap.setItemText(11, _translate("Form", "viridis"))
        self.comboBox_cmap.setItemText(12, _translate("Form", "winter"))
        self.label_2.setText(_translate("Form", "choose color normalization"))
        self.comboBox_norm.setItemText(0, _translate("Form", "default"))
        self.comboBox_norm.setItemText(1, _translate("Form", "linear"))
        self.comboBox_norm.setItemText(2, _translate("Form", "logarithm"))
        self.pushButton_adjust_cmap.setText(_translate("Form", "adjust cmap"))

from widgetImageViewDP import WidgetImageViewDP
