# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiWidgetMaskSegment2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(494, 409)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_segment2_parameter = QtWidgets.QLabel(Form)
        self.label_segment2_parameter.setObjectName("label_segment2_parameter")
        self.verticalLayout_12.addWidget(self.label_segment2_parameter)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_segment2_inner = QtWidgets.QLabel(Form)
        self.label_segment2_inner.setObjectName("label_segment2_inner")
        self.horizontalLayout_19.addWidget(self.label_segment2_inner)
        self.doubleSpinBox_segment2_inner = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_segment2_inner.setObjectName("doubleSpinBox_segment2_inner")
        self.horizontalLayout_19.addWidget(self.doubleSpinBox_segment2_inner)
        self.verticalLayout_12.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_segment2_outer = QtWidgets.QLabel(Form)
        self.label_segment2_outer.setObjectName("label_segment2_outer")
        self.horizontalLayout_20.addWidget(self.label_segment2_outer)
        self.doubleSpinBox_segment2_outer = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_segment2_outer.setObjectName("doubleSpinBox_segment2_outer")
        self.horizontalLayout_20.addWidget(self.doubleSpinBox_segment2_outer)
        self.verticalLayout_12.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_segment2_rotate_angle = QtWidgets.QLabel(Form)
        self.label_segment2_rotate_angle.setObjectName("label_segment2_rotate_angle")
        self.horizontalLayout_21.addWidget(self.label_segment2_rotate_angle)
        self.doubleSpinBox_segment2_rotate_angle = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_segment2_rotate_angle.setObjectName("doubleSpinBox_segment2_rotate_angle")
        self.horizontalLayout_21.addWidget(self.doubleSpinBox_segment2_rotate_angle)
        self.verticalLayout_12.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_segment2_open_angle = QtWidgets.QLabel(Form)
        self.label_segment2_open_angle.setObjectName("label_segment2_open_angle")
        self.horizontalLayout_22.addWidget(self.label_segment2_open_angle)
        self.doubleSpinBox_segment2_open_angle = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_segment2_open_angle.setObjectName("doubleSpinBox_segment2_open_angle")
        self.horizontalLayout_22.addWidget(self.doubleSpinBox_segment2_open_angle)
        self.verticalLayout_12.addLayout(self.horizontalLayout_22)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem)
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_12.addWidget(self.line_4)
        self.checkBox_segment2_is_center = QtWidgets.QCheckBox(Form)
        self.checkBox_segment2_is_center.setObjectName("checkBox_segment2_is_center")
        self.verticalLayout_12.addWidget(self.checkBox_segment2_is_center)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_segment2_center_j = QtWidgets.QLabel(Form)
        self.label_segment2_center_j.setObjectName("label_segment2_center_j")
        self.horizontalLayout_23.addWidget(self.label_segment2_center_j)
        self.doubleSpinBox_segment2_center_j = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_segment2_center_j.setObjectName("doubleSpinBox_segment2_center_j")
        self.horizontalLayout_23.addWidget(self.doubleSpinBox_segment2_center_j)
        self.verticalLayout_12.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_segment2_center_i = QtWidgets.QLabel(Form)
        self.label_segment2_center_i.setObjectName("label_segment2_center_i")
        self.horizontalLayout_24.addWidget(self.label_segment2_center_i)
        self.doubleSpinBox_segment2_center_i = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_segment2_center_i.setObjectName("doubleSpinBox_segment2_center_i")
        self.horizontalLayout_24.addWidget(self.doubleSpinBox_segment2_center_i)
        self.verticalLayout_12.addLayout(self.horizontalLayout_24)
        self.verticalLayout.addLayout(self.verticalLayout_12)
        self.label_segment2_inner.setBuddy(self.doubleSpinBox_segment2_inner)
        self.label_segment2_outer.setBuddy(self.doubleSpinBox_segment2_outer)
        self.label_segment2_rotate_angle.setBuddy(self.doubleSpinBox_segment2_rotate_angle)
        self.label_segment2_open_angle.setBuddy(self.doubleSpinBox_segment2_open_angle)
        self.label_segment2_center_j.setBuddy(self.doubleSpinBox_segment2_center_j)
        self.label_segment2_center_i.setBuddy(self.doubleSpinBox_segment2_center_i)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_segment2_parameter.setText(_translate("Form", "Two-segmented ring parameters"))
        self.label_segment2_inner.setText(_translate("Form", "inner radius (pix)(&I)"))
        self.label_segment2_outer.setText(_translate("Form", "outer radius (pix)(&O)"))
        self.label_segment2_rotate_angle.setText(_translate("Form", "rotation angle (deg)(&R)"))
        self.label_segment2_open_angle.setText(_translate("Form", "open angle (deg)(&A)"))
        self.checkBox_segment2_is_center.setText(_translate("Form", "centered"))
        self.label_segment2_center_j.setText(_translate("Form", "horizontal shift(&J)"))
        self.label_segment2_center_i.setText(_translate("Form", "vertical shift(&I)"))

