# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiWidgetMaskRectangle.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_rectangle_parameter = QtWidgets.QLabel(Form)
        self.label_rectangle_parameter.setObjectName("label_rectangle_parameter")
        self.verticalLayout_2.addWidget(self.label_rectangle_parameter)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_rectangle_width = QtWidgets.QLabel(Form)
        self.label_rectangle_width.setObjectName("label_rectangle_width")
        self.horizontalLayout_4.addWidget(self.label_rectangle_width)
        self.doubleSpinBox_rectangle_width = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_rectangle_width.setObjectName("doubleSpinBox_rectangle_width")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_rectangle_width)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_rectangle_height = QtWidgets.QLabel(Form)
        self.label_rectangle_height.setObjectName("label_rectangle_height")
        self.horizontalLayout_5.addWidget(self.label_rectangle_height)
        self.doubleSpinBox_rectangle_height = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_rectangle_height.setObjectName("doubleSpinBox_rectangle_height")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_rectangle_height)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_rectangle_rotation_angle = QtWidgets.QLabel(Form)
        self.label_rectangle_rotation_angle.setObjectName("label_rectangle_rotation_angle")
        self.horizontalLayout_21.addWidget(self.label_rectangle_rotation_angle)
        self.doubleSpinBox_rectangle_rotation_angle = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_rectangle_rotation_angle.setObjectName("doubleSpinBox_rectangle_rotation_angle")
        self.horizontalLayout_21.addWidget(self.doubleSpinBox_rectangle_rotation_angle)
        self.verticalLayout_2.addLayout(self.horizontalLayout_21)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.checkBox_rectangle_is_center = QtWidgets.QCheckBox(Form)
        self.checkBox_rectangle_is_center.setObjectName("checkBox_rectangle_is_center")
        self.verticalLayout_2.addWidget(self.checkBox_rectangle_is_center)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_rectangle_center_j = QtWidgets.QLabel(Form)
        self.label_rectangle_center_j.setObjectName("label_rectangle_center_j")
        self.horizontalLayout_6.addWidget(self.label_rectangle_center_j)
        self.doubleSpinBox_rectangle_center_j = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_rectangle_center_j.setObjectName("doubleSpinBox_rectangle_center_j")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_rectangle_center_j)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_rectangle_center_i = QtWidgets.QLabel(Form)
        self.label_rectangle_center_i.setObjectName("label_rectangle_center_i")
        self.horizontalLayout_7.addWidget(self.label_rectangle_center_i)
        self.doubleSpinBox_rectangle_center_i = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_rectangle_center_i.setObjectName("doubleSpinBox_rectangle_center_i")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_rectangle_center_i)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.label_rectangle_width.setBuddy(self.doubleSpinBox_rectangle_width)
        self.label_rectangle_height.setBuddy(self.doubleSpinBox_rectangle_height)
        self.label_rectangle_rotation_angle.setBuddy(self.doubleSpinBox_rectangle_rotation_angle)
        self.label_rectangle_center_j.setBuddy(self.doubleSpinBox_rectangle_center_j)
        self.label_rectangle_center_i.setBuddy(self.doubleSpinBox_rectangle_center_i)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_rectangle_parameter.setText(_translate("Form", "Rectangle Parameters"))
        self.label_rectangle_width.setText(_translate("Form", "rectangular width(&W)"))
        self.label_rectangle_height.setText(_translate("Form", "rectangular height(&H)"))
        self.label_rectangle_rotation_angle.setText(_translate("Form", "rotation angle(&R)"))
        self.checkBox_rectangle_is_center.setText(_translate("Form", "centered"))
        self.label_rectangle_center_j.setText(_translate("Form", "horizontal shift(&J)"))
        self.label_rectangle_center_i.setText(_translate("Form", "vertical shift(&I)"))

